@startuml clases

title Diagrama de Clases

'!theme amiga
skinparam backgroundColor white
skinparam defaultFontName Arial

hide empty members

entity User 
{
    Username
    Password
    Roles
}

entity Role{
    Name
    Permissions
}

entity Permission{
    Name
    ModulesIds
}

entity Module{
    Name
    Description
}

entity InternShip{
    CompanyName
    userId
    CompanyId
    Address
    Description
    WorkingHours
    Requirements
    Salary
    StartDate
    EndDate
}

entity Application {
    InternShipId
    UserId
    Status
}

User o- Role
Role o- Permission
Permission o- Module

Application *-- InternShip
Application *-up- User

InternShip *-up- User



@enduml

